locale/es.yml
Add Spanish (Spain) translation
=> Add Spanish (Spain) translation

locale/ru.yml
Add initial Russian language translation
=> Add initial Russian language translation

locale/es.yml
Add strings for:
- WiFi setup
- Notification toggle
- LoRa toggle on home screen
=> update Spanish strings to 2.5.8

locale/se.yml
Update swedish translations
```yml
silent: ~
'WiFi: <not setup>': ~
'Lock: off/off': ~
LoRa TX off!: ~
WiFi SSID: ~
WiFi pre-shared Key: ~
Settings Lock: ~
'Lock: %s/%s': ~
Enter Text ...: ~
'!Enter Filter ...': ~
Enter Filter ...: ~
'WiFi: %s': ~
<not set>: ~
region unset: ~
Banner & Sound: ~
Banner only: ~
Sound only: ~
```
=> feat: Update swedish translations

locale/zh-CN.yml
Add 130 translations for Chinese (Simplified) for the lvgl i18n.
=> feat: Add Simplified Chinese translation for lv_i18n

locale/fr.yml, locale/lv_i18n.c, locale/lv_i18n.h
It's nothing and you probably already know but translations are not working for BT programming mode ;)
=> fix: Update french

source/graphics/TFT/TFTView_320x240.cpp
=> feat: imperial units support

maps/README.md
I just read your comment in the readme, thanks a lot 🙏 
I would like to add teddy1602 who downloaded most part of the tiles and sent it to me. 
Then I started to create torrents to share them.
I also setup temporarily an oracle cloud VM with 2Gbps to boost seeders at the beginning. If new torrents are shared, I can also help them to seed.
=> chore: Update maps README.md - thanks to teddy1602

source/graphics/TFT/TFTView_320x240.cpp
=> feat: disable wifi before entering BT programming mode

source/graphics/TFT/TFTView_320x240.cpp, source/graphics/common/ViewController.cpp
=> fix ack for channel

source/graphics/TFT/TFTView_320x240.cpp
=> fix: node resize animation

extra_script.py, library.json
Addendum to #64 -- Fix `src_filter` so it functions correctly. This particular piece *must* be "replaced" rather than "appended" from the library.json.
This is tested and working now :tada:
=> build: PIO - Replace srcFilter, set srcDir, includeDir. Add Thread dependency

source/graphics/TFT/TFTView_320x240.cpp
=> fix: lora frequency offset

source/graphics/TFT/TFTView_320x240.cpp
=> fix: locked reboot screen

.github/dependabot.yml, .github/workflows/action-semantic-pull-request.yml, .github/workflows/greetings.yml, .github/workflows/main.yml, .github/workflows/nightly.yml, .github/workflows/trunk_check.yml, library.json
Just some janitor work :broom: 
- Add Dependabot
- Add Trunk Upgrade Nightly Task (Dependabot for Trunk)
- Fix `external-lvgl` to use the official package name -- `lvgl/lvgl`
- Fix `Thread` package name/version to use Meshtastic's [ArduinoThread](https://github.com/meshtastic/ArduinoThread) fork
- Fix Trunk complaints in the `.github` directory
=> chore: Setup Dependabot, Trunk Upgrades, and trunk fmt Actions

source/graphics/TFT/TFTView_320x240.cpp
=> fix: wifi button behavior

source/graphics/TFT/TFTView_320x240.cpp
map style dropdown is empty when returning to map
=> fix: map style dropdown

CMakeLists.txt, include/graphics/map/GeoPoint.h, include/graphics/map/MapPanel.h, include/graphics/map/TileService.h, include/graphics/view/TFT/TFTView_320x240.h, include/util/ILog.h, source/graphics/TFT/TFTView_320x240.cpp, source/graphics/map/MapPanel.cpp, source/graphics/map/MapTile.cpp, tests/test_MapPanel.cpp
Added unit tests for map scrolling
=> fix: map scrolling

README.md, generated/ui_320x240/screens.c, generated/ui_320x240/screens.h, include/util/FileLoader.h, source/graphics/TFT/TFTView_320x240.cpp, source/util/FileLoader.cpp, studio/320x240/TFT320x240.eez-project
1 place image with 100-150 pixel width under `/data/boot/logo.png`
2a  `pio run --target buildfs  -e <target env>` to build the `littlefs.bin` or
2b  `pio run --target uploadfs  -e <target env>` to flash the target (make a backup beforehand!)
=> feat: customizable boot logo

include/graphics/map/GeoPoint.h, include/graphics/map/MapPanel.h, source/graphics/TFT/TFTView_320x240.cpp, source/graphics/map/MapPanel.cpp
filter map location pins according node list filtering
pin locations counter now also considers clipped tiles
=> feat: filter map location pins according node filtering

include/graphics/view/TFT/TFTView_320x240.h, source/graphics/TFT/TFTView_320x240.cpp
resolves https://www.reddit.com/r/meshtastic/comments/1jt5qs0/seeed_indicator_mui/
=> feat: message panel keyboard placement and animation

include/graphics/view/TFT/TFTView_320x240.h, source/graphics/TFT/TFTView_320x240.cpp
click on chat jumps to node list and reveals more details
closes #106
=> show node on chat clicked

source/graphics/TFT/TFTView_320x240.cpp
=> fix: set bluetooth fixedPin to random value (restart menu)

source/graphics/TFT/TFTView_320x240.cpp
=> fix: confirmation dialog to revert to former UI

source/graphics/common/LoRaPresets.cpp
=> fix: default slot

include/graphics/LGFX/LGFX_T_DECK.h, include/graphics/driver/LGFXDriver.h
=> fix: workaround: T-Deck 100% brightness issue

source/graphics/TFT/TFTView_320x240.cpp
=> feat: 12h clock on home screen

generated/ui_320x240/screens.c, source/graphics/common/LoRaPresets.cpp, studio/320x240/TFT320x240.eez-project
Due to https://github.com/meshtastic/firmware/pull/7036
=> ANZ_433 support

include/graphics/view/TFT/TFTView_320x240.h, source/graphics/TFT/TFTView_320x240.cpp
especially for SenseCAP Indicator
=> fix: increase group/chat button size for larger displays

source/graphics/TFT/TFTView_320x240.cpp
Fixes https://github.com/meshtastic/device-ui/issues/45
Quoting my post there:
> This happens, AFAICT (at least on TFTView_320x240), when MUI gets a channel number of 0 (it's supposed to be 1 or more, 0 signifies "calculate locally from channel hash").
> 
> The code calculating frequency uses the channel, `channel - 1` rather, and as channel is a uint32, it overflows, calculating frequency numbers to the likes of 1073742720 MHz.
> 
> The code decides to not display frequency values smaller than 1 or larger than 100000 MHz, and in all cases where it does that, it says "region unset". Annoyingly/amusingly this also is not a surefire way to detect if region is unset, I think this could still display a number when region is set.
> 
> There's code that calculates the channel number from the …
=> fix: display of LoRa frequency on TFTView_320x240

source/graphics/common/ViewController.cpp
=> fix: detection sensor message
